backend:
  name: git-gateway
  repo: roosyak/bscrimea-hugo
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
collections:
  - name: 'company'
    label: 'Компании'
    folder: 'content/company'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Адресс', name: 'address', widget: 'string' }
      - { label: 'Сайт', name: 'site', widget: 'string' }
      - { label: 'Город', name: 'town', widget: 'string' }
      - { label: 'mail', name: 'mail', widget: 'string' }
      - { label: 'Телефон', name: 'tel', widget: 'list' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

